## Parent image
FROM python:3.10-slim

## Essential environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

## Work directory inside the docker container
WORKDIR /app

## Installing system dependancies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

## Copying ur all contents from local to app
COPY . .

## Run setup.py
RUN pip install --no-cache-dir -e .

# Used PORTS
EXPOSE 8501

# Run the app 
CMD ["streamlit", "run", "application.py", "--server.port=8501", "--server.address=0.0.0.0","--server.headless=true"]



 	# •	FROM → base image (lightweight + specific Python version).
	# •	ENV → make Python behave well in Docker (logging, no bytecode).
	# •	WORKDIR → keeps container filesystem tidy.
	# •	RUN apt-get → installs build tools & curl.
	# •	COPY → bring in your code.
	# •	RUN pip install → install your app & dependencies.
	# •	EXPOSE → declare app port.
	# •	CMD → run the Streamlit app when container starts.